# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5713db2a50f3ed4f0a9ec2fda9bd518b8a2ff4ee8a38548f4c9d3b587f6200d51ce9c0a92b5a7e58f5ecbe8f57c2b561d8f4268ce0b00e48a13cd23f592b88
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

test:
  secret_key_base: 50644d003418fc0dd9d699a11177ba29bb6797b2e62f26c2f6993e3592f6d85ba543a979db86c9e8a27d86bda74a983afe8e26f7d805850667dd23aaf229ab11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 171c536ca48cb958aaadb178553daeb9e976080bfd8bb233e1e7290f2165f6037f1ff5cfc67073c7cdb2bca140509490cf82a5546384ea2586ea58056ca98c4e
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
